catalog:
  typescript: 'npm:@typescript/typescript6@^6.0.2'
  '@typescript/native': 'npm:typescript@^7.0.2'

overrides:
  '@nbilyk/downlevel-dts>typescript': 'catalog:'

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@livekit/*'
