blank_issues_enabled: false
contact_links:
  - name: Slack Community Chat
    url: https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg
    about: Ask questions and discuss with other LiveKit users in real time.