blank_issues_enabled: false
contact_links:
  - name: Slack Community Chat
    url: https://join.slack.com/t/livekit-users/shared_invite/zt-19nswkhip-4Y56hpIHM94EyWUpRH1GGQ
    about: Ask questions and discuss with other LiveKit users in real time.