/**
 * An enum of first party livekit attributes generated by the serverside agents sdk.
 *
 * These keys also appear on the generated `AgentAttributes` / `TranscriptionAttributes` interfaces
 * in `src/room/attribute-typings.ts`. That file is generated from
 * https://github.com/livekit/attribute-definitions and cannot reference this enum, so the two are
 * maintained in parallel - treat the attribute definitions repo as the source of truth if they
 * ever disagree.
 */
export enum ParticipantAgentAttributes {
  AgentState = 'lk.agent.state',
  PublishOnBehalf = 'lk.publish_on_behalf',

  TranscriptionFinal = 'lk.transcription_final',
  TranscriptionSegmentId = 'lk.segment_id',
  TranscribedTrackId = 'lk.transcribed_track_id',

  Expression = 'lk.expression',
}
