name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
    - name: Use Node.js 24
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: ESLint
      run: pnpm lint
    
    - name: Prettier
      run: pnpm format:check

    - name: Throws check
      run: pnpm throws:check

    - name: Run Tests
      run: pnpm test

    - name: Check browser target compatibility
      run: |
        pnpm build
        pnpm compat

    - name: Ensure package publish is configured correctly
      run: pnpm publint
